//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the blackfly package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __blackfly__BLACKFLYCONFIG_H__
#define __blackfly__BLACKFLYCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace blackfly
{
  class BlackFlyConfigStatics;

  class BlackFlyConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(BlackFlyConfig &config, const BlackFlyConfig &max, const BlackFlyConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const BlackFlyConfig &config1, const BlackFlyConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, BlackFlyConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const BlackFlyConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, BlackFlyConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const BlackFlyConfig &config) const = 0;
      virtual void getValue(const BlackFlyConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T BlackFlyConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T BlackFlyConfig::* field;

      virtual void clamp(BlackFlyConfig &config, const BlackFlyConfig &max, const BlackFlyConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const BlackFlyConfig &config1, const BlackFlyConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, BlackFlyConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const BlackFlyConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, BlackFlyConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const BlackFlyConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const BlackFlyConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, BlackFlyConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, BlackFlyConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<BlackFlyConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(BlackFlyConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("cam_id"==(*_i)->name){cam_id = boost::any_cast<int>(val);}
        if("acquisition_start"==(*_i)->name){acquisition_start = boost::any_cast<bool>(val);}
        if("acquisition_stop"==(*_i)->name){acquisition_stop = boost::any_cast<bool>(val);}
        if("fps"==(*_i)->name){fps = boost::any_cast<double>(val);}
        if("enable_gamma"==(*_i)->name){enable_gamma = boost::any_cast<bool>(val);}
        if("gamma"==(*_i)->name){gamma = boost::any_cast<double>(val);}
        if("exposure_auto"==(*_i)->name){exposure_auto = boost::any_cast<int>(val);}
        if("exposure_time"==(*_i)->name){exposure_time = boost::any_cast<int>(val);}
        if("gain_auto"==(*_i)->name){gain_auto = boost::any_cast<int>(val);}
        if("gain"==(*_i)->name){gain = boost::any_cast<int>(val);}
        if("binning_mode"==(*_i)->name){binning_mode = boost::any_cast<int>(val);}
        if("binning"==(*_i)->name){binning = boost::any_cast<int>(val);}
        if("lighting_mode"==(*_i)->name){lighting_mode = boost::any_cast<int>(val);}
        if("auto_exposure_priority"==(*_i)->name){auto_exposure_priority = boost::any_cast<int>(val);}
      }
    }

    int cam_id;
bool acquisition_start;
bool acquisition_stop;
double fps;
bool enable_gamma;
double gamma;
int exposure_auto;
int exposure_time;
int gain_auto;
int gain;
int binning_mode;
int binning;
int lighting_mode;
int auto_exposure_priority;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int cam_id;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool acquisition_start;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool acquisition_stop;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double fps;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool enable_gamma;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double gamma;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int exposure_auto;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int exposure_time;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int gain_auto;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int gain;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int binning_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int binning;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int lighting_mode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int auto_exposure_priority;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("BlackFlyConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const BlackFlyConfig &__max__ = __getMax__();
      const BlackFlyConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const BlackFlyConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const BlackFlyConfig &__getDefault__();
    static const BlackFlyConfig &__getMax__();
    static const BlackFlyConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const BlackFlyConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void BlackFlyConfig::ParamDescription<std::string>::clamp(BlackFlyConfig &config, const BlackFlyConfig &max, const BlackFlyConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class BlackFlyConfigStatics
  {
    friend class BlackFlyConfig;

    BlackFlyConfigStatics()
    {
BlackFlyConfig::GroupDescription<BlackFlyConfig::DEFAULT, BlackFlyConfig> Default("Default", "", 0, 0, true, &BlackFlyConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.cam_id = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.cam_id = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.cam_id = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("cam_id", "int", 0, "id of the camera to change the settings", "", &BlackFlyConfig::cam_id)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("cam_id", "int", 0, "id of the camera to change the settings", "", &BlackFlyConfig::cam_id)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.acquisition_start = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.acquisition_start = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.acquisition_start = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<bool>("acquisition_start", "bool", 0, "start frame acquisition", "", &BlackFlyConfig::acquisition_start)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<bool>("acquisition_start", "bool", 0, "start frame acquisition", "", &BlackFlyConfig::acquisition_start)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.acquisition_stop = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.acquisition_stop = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.acquisition_stop = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<bool>("acquisition_stop", "bool", 0, "stop frame acquisition", "", &BlackFlyConfig::acquisition_stop)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<bool>("acquisition_stop", "bool", 0, "stop frame acquisition", "", &BlackFlyConfig::acquisition_stop)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.fps = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.fps = 50.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.fps = 20.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<double>("fps", "double", 0, "change frame rate", "", &BlackFlyConfig::fps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<double>("fps", "double", 0, "change frame rate", "", &BlackFlyConfig::fps)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enable_gamma = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enable_gamma = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enable_gamma = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<bool>("enable_gamma", "bool", 0, "enable/disable gamma", "", &BlackFlyConfig::enable_gamma)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<bool>("enable_gamma", "bool", 0, "enable/disable gamma", "", &BlackFlyConfig::enable_gamma)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gamma = 0.25;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gamma = 4.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gamma = 1.0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<double>("gamma", "double", 0, "set gamma value", "", &BlackFlyConfig::gamma)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<double>("gamma", "double", 0, "set gamma value", "", &BlackFlyConfig::gamma)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.exposure_auto = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.exposure_auto = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.exposure_auto = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("exposure_auto", "int", 0, "change auto exposure type", "{'enum': [{'name': 'ExposureAuto_Off', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureAuto_Off', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExposureAuto_Once', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureAuto_Once', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExposureAuto_Continuous', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureAuto_Continuous', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set auto exposure mode'}", &BlackFlyConfig::exposure_auto)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("exposure_auto", "int", 0, "change auto exposure type", "{'enum': [{'name': 'ExposureAuto_Off', 'type': 'int', 'value': 0, 'srcline': 27, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureAuto_Off', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExposureAuto_Once', 'type': 'int', 'value': 1, 'srcline': 28, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureAuto_Once', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExposureAuto_Continuous', 'type': 'int', 'value': 2, 'srcline': 29, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureAuto_Continuous', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set auto exposure mode'}", &BlackFlyConfig::exposure_auto)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.exposure_time = 12;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.exposure_time = 500000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.exposure_time = 20000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("exposure_time", "int", 0, "change exposure time (Must first set ExposureAuto_Off)", "", &BlackFlyConfig::exposure_time)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("exposure_time", "int", 0, "change exposure time (Must first set ExposureAuto_Off)", "", &BlackFlyConfig::exposure_time)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gain_auto = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gain_auto = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gain_auto = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("gain_auto", "int", 0, "change auto gain type", "{'enum': [{'name': 'GainAuto_Off', 'type': 'int', 'value': 0, 'srcline': 38, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'GainAuto_Off', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'GainAuto_Once', 'type': 'int', 'value': 1, 'srcline': 39, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'GainAuto_Once', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'GainAuto_Continuous', 'type': 'int', 'value': 2, 'srcline': 40, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'GainAuto_Continuous', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set auto gain mode'}", &BlackFlyConfig::gain_auto)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("gain_auto", "int", 0, "change auto gain type", "{'enum': [{'name': 'GainAuto_Off', 'type': 'int', 'value': 0, 'srcline': 38, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'GainAuto_Off', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'GainAuto_Once', 'type': 'int', 'value': 1, 'srcline': 39, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'GainAuto_Once', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'GainAuto_Continuous', 'type': 'int', 'value': 2, 'srcline': 40, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'GainAuto_Continuous', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set auto gain mode'}", &BlackFlyConfig::gain_auto)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gain = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gain = 46;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gain = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("gain", "int", 0, "change gain (Must first set ExposureGain_Off)", "", &BlackFlyConfig::gain)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("gain", "int", 0, "change gain (Must first set ExposureGain_Off)", "", &BlackFlyConfig::gain)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.binning_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.binning_mode = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.binning_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("binning_mode", "int", 0, "change binning type", "{'enum': [{'name': 'Average', 'type': 'int', 'value': 0, 'srcline': 49, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Average', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Sum', 'type': 'int', 'value': 1, 'srcline': 50, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Sum', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set binning mode'}", &BlackFlyConfig::binning_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("binning_mode", "int", 0, "change binning type", "{'enum': [{'name': 'Average', 'type': 'int', 'value': 0, 'srcline': 49, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Average', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Sum', 'type': 'int', 'value': 1, 'srcline': 50, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Sum', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set binning mode'}", &BlackFlyConfig::binning_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.binning = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.binning = 4;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.binning = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("binning", "int", 0, "change binning", "", &BlackFlyConfig::binning)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("binning", "int", 0, "change binning", "", &BlackFlyConfig::binning)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.lighting_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.lighting_mode = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.lighting_mode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("lighting_mode", "int", 0, "change lighting type", "{'enum': [{'name': 'Normal', 'type': 'int', 'value': 0, 'srcline': 59, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Normal', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Backlight', 'type': 'int', 'value': 1, 'srcline': 60, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Backlight', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Frontlight', 'type': 'int', 'value': 2, 'srcline': 61, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Frontlight', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set lighting mode'}", &BlackFlyConfig::lighting_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("lighting_mode", "int", 0, "change lighting type", "{'enum': [{'name': 'Normal', 'type': 'int', 'value': 0, 'srcline': 59, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Normal', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Backlight', 'type': 'int', 'value': 1, 'srcline': 60, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Backlight', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Frontlight', 'type': 'int', 'value': 2, 'srcline': 61, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Frontlight', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set lighting mode'}", &BlackFlyConfig::lighting_mode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.auto_exposure_priority = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.auto_exposure_priority = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.auto_exposure_priority = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("auto_exposure_priority", "int", 0, "change auto exposure priority type", "{'enum': [{'name': 'Gain', 'type': 'int', 'value': 0, 'srcline': 67, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Gain', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExposureTime', 'type': 'int', 'value': 1, 'srcline': 68, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureTime', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set auto exposure priority mode'}", &BlackFlyConfig::auto_exposure_priority)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(BlackFlyConfig::AbstractParamDescriptionConstPtr(new BlackFlyConfig::ParamDescription<int>("auto_exposure_priority", "int", 0, "change auto exposure priority type", "{'enum': [{'name': 'Gain', 'type': 'int', 'value': 0, 'srcline': 67, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'Gain', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'ExposureTime', 'type': 'int', 'value': 1, 'srcline': 68, 'srcfile': '/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg', 'description': 'ExposureTime', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum to set auto exposure priority mode'}", &BlackFlyConfig::auto_exposure_priority)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(BlackFlyConfig::AbstractGroupDescriptionConstPtr(new BlackFlyConfig::GroupDescription<BlackFlyConfig::DEFAULT, BlackFlyConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<BlackFlyConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<BlackFlyConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<BlackFlyConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    BlackFlyConfig __max__;
    BlackFlyConfig __min__;
    BlackFlyConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const BlackFlyConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static BlackFlyConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &BlackFlyConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const BlackFlyConfig &BlackFlyConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const BlackFlyConfig &BlackFlyConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const BlackFlyConfig &BlackFlyConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<BlackFlyConfig::AbstractParamDescriptionConstPtr> &BlackFlyConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<BlackFlyConfig::AbstractGroupDescriptionConstPtr> &BlackFlyConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const BlackFlyConfigStatics *BlackFlyConfig::__get_statics__()
  {
    const static BlackFlyConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = BlackFlyConfigStatics::get_instance();

    return statics;
  }

//#line 27 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_ExposureAuto_Off = 0;
//#line 28 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_ExposureAuto_Once = 1;
//#line 29 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_ExposureAuto_Continuous = 2;
//#line 38 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_GainAuto_Off = 0;
//#line 39 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_GainAuto_Once = 1;
//#line 40 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_GainAuto_Continuous = 2;
//#line 49 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_Average = 0;
//#line 50 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_Sum = 1;
//#line 59 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_Normal = 0;
//#line 60 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_Backlight = 1;
//#line 61 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_Frontlight = 2;
//#line 67 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_Gain = 0;
//#line 68 "/home/oveggeland/Desktop/my_ws/src/blackfly_nodelet/cfg/BlackFly.cfg"
      const int BlackFly_ExposureTime = 1;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __BLACKFLYRECONFIGURATOR_H__
